### ISSUE TITLE
Select All

### ISSUE THREAD

**Issue by smaragdus** [ericpromislow/tabhunter#100]
I think that `Select All` button would be handy for a couple of use cases:

- to copy all URLs;
- to close tabs;

To close all tabs the user can just open a new window and close the previous one but if the user wants to keep for example just 2 of 10 open tab and close the other 8 tabs it would be faster to select all the tabs and then deselect the 2 ones they want to keep than selecting 8 tabs manually.

As an alternative to `Select All` button `CTRL+A` shortcut command might be added to select all tabs, now it selects all the text inside **Tabhunter** pop-up window.

**Comment by ericpromislow** [comment]
Not a bad idea. Thanks for the feedback.

**Comment by ericpromislow** [comment]
Done in 3fef9d7

**Comment by smaragdus** [comment]
@ericpromislow 

Thank you for implementing `Select All` button, I have just checked [Tabhunter](https://github.com/ericpromislow/tabhunter) version **3.1.2** and it works fine.

I may open one more issue regarding a new option in preferences.

Have a great summer!

Regards
