### ISSUE TITLE
Restrict search to current window, display window numbers and tab numbers

### ISSUE THREAD

**Issue by reikred** [ericpromislow/tabhunter#103]
I often find myself wanting to search for a tab, but only among the tabs of the current window. I think this would be a useful feature. Selecting this filtering behavior could be a checkbox near the "audio only" checkbox, for example. Or selecting the filter could be some prefix like # or @ in the search term...but that might interfere with some searches.

**Comment by ericpromislow** [comment]
You can do this right now, although you need to know the window # of the current window, by putting `{w:WINDOWNUMBER}` or `{w:WINDOWNUMBER:STARTTAB-ENDTAB}` at the start of your pattern, like `{w:3:5-8}`

The first colon is optional, by the way.
