### ISSUE TITLE
Feature Request: short delay on keypress in search bar to reduce lag during typing

### ISSUE THREAD

**Issue by Semnodime** [ericpromislow/tabhunter#104]
_Disclaimer: This might be an rare edge case, but I usually have 1000-3000 tabs opened._

When typing in the search bar, **on every key press the search result is updated** (and attempts to render) immediately. This obviously also happens during typing. Therefore when trying to enter my full search phrase, **there is some noticable lag on the first few key presses**, till the search result count is low enough to cause no recognizable lag during typing the remaining characters.

To make the search experience a bit more fluent **I therefore request an option to add a few millisecond delay (50-100ms?) before searching ( or rendering ) the results** to allow for no lag during typing.

Alternatively, the amount of rendered entries in the search result could be limited to say 20 tabs and only after few millisecond delay the rest of the list is loaded. This should also eliminate the lag, as it is probably caused during rendering (updating the scrolldown result entry list) and not by the search itself.

**Feedback and Comments kindly requested.**

**Comment by ericpromislow** [comment]
Sounds like a good idea. I've done that exact thing with other Javascript apps. I'll probably add a pref for this to turn it on because most people don't typically have that many tabs opened (I start closing tabs when I hit 300).

**Comment by benryanau** [comment]
ta!

**Comment by ericpromislow** [comment]
Fixed in a6d3fb0, version 3.2.2

Kicks in when you have >= 1000 tabs loaded.

The delay starts at 100 msec and increases with log10 of the # of tabs, cuz why not
