### ISSUE TITLE
Feature Request: refresh tabs

### ISSUE THREAD

**Issue by Sada-Mio** [ericpromislow/tabhunter#106]
ability to refresh selected tabs

**Comment by a-pirard** [comment]
On 15/04/2020 14.42, Sada-Mio wrote:
    
    
      
      ability to refresh selected tabs
    
    If I understand your 4 words, Tab Reloader does it.

**Comment by Sada-Mio** [comment]
I want to select tabs matched by tabhunter to refresh. 

Right now the only option is to close/move tab.

**Comment by ericpromislow** [comment]
Looks like a reasonable request

**Comment by ericpromislow** [comment]
Done in version 3.1.1, git commit 6d22068
