### ISSUE TITLE
Ctrl-Shift-S shortcut stolen by screenshot (firefox)

### ISSUE THREAD

**Issue by reikred** [ericpromislow/tabhunter#109]
In win10/firefox, the Ctrl-Shift-S shortcut does not work because it has been taken by the (built-in firefox?) screenshot tool. 

Do you have any workaround suggestion for a usable key sequence? I'd love to have Ctrl-Shift-5 (five)  work also in win10 but I do not know how to steal that shortcut away from "move to tab 5 (five)".

**Comment by ericpromislow** [comment]
You should be able to set an unreserved startup sequence in tabhunter prefs. I don't have a windows 10 box to test on though.

**Comment by reikred** [comment]
I don't know ANY unreserved sequences. Can someone make a suggestion?

**Comment by reikred** [comment]
I think there is a bug that attempting to create a new shortcut sequence does not work.  And this was supposedly fixed once before, see 

https://github.com/ericpromislow/tabhunter/issues/92

Current platform: win10, firefox 80.0 (which is the latest at the time of this writing).

**Comment by reikred** [comment]
I'd reopen this issue  if i knew how, but it appears I cannot.
