### ISSUE TITLE
Stopped working with Waterfox Classic (Firefox 56)

### ISSUE THREAD

**Issue by ElhemEnohpi** [ericpromislow/tabhunter#110]
Thanks for the great addon, I've been using it a long time. Unfortunately it stopped working in my browser some weeks (months?) ago, not sure if it was a result of a browser or tabhunter update. I'm using Waterfox Classic, which is a fork of Firefox 56 with security updates backported. When I try to search, no results are found, and it says "Matched 0/0 tabs".

I tested with a new profile, and no other extensions installed. I'm using macOS 10.14.6. It happens 100% of the time, not only under low memory conditions etc.

In the browser console I see this, the first line when I open the popup window, and the second when I type something:
```
TypeError: browser.theme is undefined[Learn More]  tabhunter.js:218:5
TypeError: this.doneFunc is not a function[Learn More] tabhunter.js:903:13
	makeListFromMatchedItems moz-extension://69a292b6-b401-7843-8331-4e248d09bfaa/popup/tabhunter.js:903:13
	makeListFromMatchedItems moz-extension://69a292b6-b401-7843-8331-4e248d09bfaa/popup/tabhunter.js:804:5
	onPatternChanged moz-extension://69a292b6-b401-7843-8331-4e248d09bfaa/popup/tabhunter.js:710:5
```
I'd love to have it working again! But I understand if you don't want to support such an old browser.

**Comment by ericpromislow** [comment]
Yup, it's just me on this (so far). Apparently this browser doesn't expose themes, but current firefox and chrome do, so I won't change that.  As for the `this.doneFunc` not set, it looks like this browser is way behind in JavaScript versions too. Afraid you're on your own with this one.

**Comment by ElhemEnohpi** [comment]
No problem, I thought maybe it was an easy fix... Yes that browser is very out of date now. I've mostly stopped using it, but there are a couple of legacy addons that I need to access once in a while. Tabhunter is working fine for me in the latest Firefox.
