### ISSUE TITLE
Option to add custom CSS

### ISSUE THREAD

**Issue by r-a-y** [ericpromislow/tabhunter#114]
Thanks for such a useful addon.

It would be great if there was the ability for users to add custom CSS for the popup. This can be an additional option to the `prefs.html` page.

Some things that could be done via CSS include hiding some elements and resizing the popup window (see #76, #94). If you're interested in this feature, I can work on a pull request.

**Comment by ericpromislow** [comment]
A pull request is always welcome, and probably the only way this is going to happen. Tabhunter is about 16 years old now and works fine for me. The design of the advanced page gets to me, but there are too many other things grabbing my free time to have me sit down and do the renovation. Same with the prefs page.

Also, I have a feeling the popup window is at its maximum size. But if you find a way to increase it, that would be great.  But since Firefox moved to the webextensions API there are more restrictions on the UI.

**Comment by r-a-y** [comment]
> But if you find a way to increase it, that would be great.

I experimented with some custom CSS. Here's a screenshot:

![2021-06-04_135837](https://user-images.githubusercontent.com/505921/120862075-dc231980-c577-11eb-89af-2d5103793cee.png)

Popup size is around 800 x 600.

Before creating this issue, I actually added a variation of the following CSS to the bottom of `tabhunter.css`, but I figured out a way to persist my changes with `userContent.css`.

<details><summary>Click to view custom CSS for userContent.css</summary>

```
/* tabhunter */
@-moz-document url("moz-extension://da2ae89b-adca-4055-983c-d2109c70782e/popup/tabhunter.html") {
	body {
		width: 800px !important;
	}
	
	div#form {
		width: 100% !important;
		border: 0 !important;
		margin-top: .3em;
	}
	
	#main {
		margin-bottom: -1em;
	}
	
	#activity {
		font-size: 11.5px !important;
	}
	
	ul {
	    height: 505px !important;
	    margin-top: 0em;
	}
	
	.row + .row,
	#showSearchTextPanel,
	#selectAllButton {
		display: none;
	}
}
```
</details>

The problem is not everybody will want the same UI as me, so that's why I recommended a custom CSS textarea option. However, now that I can just add my custom CSS to `userContent.css`, adding a pull request isn't a priority for me anymore.

For those stumbling into this issue, to enable and use `userContent.css`, follow the information here: https://wiki.archlinux.org/title/Firefox/Tweaks#General_user_interface_CSS_settings

Going to close this one. Definitely understand about other projects taking priority. Thanks for maintaining the addon all these years!
