### ISSUE TITLE
Neglect Sort in Chrome

### ISSUE THREAD

**Issue by BillDorn** [ericpromislow/tabhunter#118]
https://github.com/ericpromislow/tabhunter/issues/90
Is there a way to use neglect sort in Chrome version?

**Comment by ericpromislow** [comment]
Not until chrome supports the `Tab.lastAccessed` property.

References:
Firefox: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab#lastAccessed
Chrome: https://developer.chrome.com/docs/extensions/reference/tabs/#type-Tab

**Comment by ericpromislow** [comment]
Spring 2023 and `tab.lastAccessed` is still supported only for firefox & firefox-android (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab#browser_compatibility), so closing this request
