### ISSUE TITLE
Tabhunter dialog doesn't remember positioning

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ericpromislow/tabhunter#12]
```
What steps will reproduce the problem?
1. Use Ctrl+Alt+T to open Tabhunter
2. Move the dialog to the desired location
3. Use Close or Go buttons, Esc, Enter, or simple close the Tabhunter
window with the window manager.
4. Use Ctrl+Alt+T to open Tabhunter.

What is the expected output? What do you see instead?

I would expect Tabhunter to appear in the position on my screen where I
placed it in step 2.

What version of the product are you using? On what operating system?

0.6.3 on openSUSE 11.0.
```

Original issue reported on code.google.com by `sanforda...@gmail.com` on 15 Jul 2008 at 8:11

**Comment by wsmwk** [comment]
can someone alter the title of this issue so it explicitly calls out linux-only?

**Comment by ericpromislow** [comment]
Should be fixed now that Tabhunter is targeting the webextensions API. To test before the next release, use the Firefox Developers' Edition, `about:debugging`, load a temporary addon, pull up the tabhunter `manifest.json` file, and load by either pressing `Shift-Ctrl-T` or hitting the icon, now in the upper right bar.
