### ISSUE TITLE
Tabhunter 3.5.0 breaks usage of Delete/Backspace to delete characters

### ISSUE THREAD

**Issue by potassiumchloride** [ericpromislow/tabhunter#121]
Hello,

the new version 3.5.0 introduced Backspace/Delete to close selected tabs, but now it is impossible to use these keys in the pattern field to delete characters because they simply do nothing, i.e. you cannot delete any text.

**Comment by ericpromislow** [comment]
Reproduced. I'll fix it tonight

**Comment by ericpromislow** [comment]
Fixed in version 3.5.2

**Comment by potassiumchloride** [comment]
Confirmed, in 3.5.2 it's working again. Thanks for the fix!
