### ISSUE TITLE
recent Tabhunter update doesn't autorefresh url list with existing search term

### ISSUE THREAD

**Issue by mikec39** [ericpromislow/tabhunter#122]
I use Tabhunter routinely, and it's been very helpful.   Recently, however, its behaviour has changed.  If I have an existing search term set from a previous invocation of Tabhunter, and later I re-invoke Tabhunter, there are no resulting "found" urls shown for that previous search term.  I now have to modify the existing search term before Tabhunter will show me the found urls.   

This is definitely a nuisance, not a benefit, since I often go repeatedly into Tabhunter to work my way through a set of urls matching a single original search term.  To have to keep restating that search term (even if just by deleting the last letter and retyping it) is a pain.

Can the original behaviour be restored?  Or at least made a user option?  Right now Tabhunter seems to be optimized to prefer a new search term with every invocation.

**Comment by ericpromislow** [comment]
I haven't seen this, possibly since this feature ended up in version 1. On my main platform, Firefox on macOS, I just invoked Tabhunter, and my most recent search term was right there.

Which browser+version+platform is this for?

**Comment by deadcombo** [comment]
I can't replicate this on Windows, Firefox 115.0a1.
Perhaps I misunderstood the issue but when I input a search term, close the popup or switch to the tab in the popup and then reinvoke the popup, the search term remains and the tabs remain filtered.

**Comment by mikec39** [comment]
I'm using the latest production Firefox 113.0.2.   Since approximately the
last public release of Tabhunter (3.5.2), I've been seeing the search term
remain in Tabhunter on reinvocation, but without the list of displayed
matching urls.  To see the matching urls for the given search term I have
to modify that search term (eg. delete the last letter in the search term
and retype it).

Perhaps this is something that's a function of the particular version of
Firefox, possibly the 113.x series (since it's not new to 113.0.2).  Or it
may be a problem with the specific Tabhunter version.

...Mike

**Comment by ericpromislow** [comment]
Not seeing this on Firefox 113.0.2 on macOS, FF 112.0.2 on Ubuntu, and 113.0.2 on Windows. Maybe a reinstall (of tabhunter, not the browser or the whole OS) will fix it. Maybe it's due to another extension, but it definitely doesn't look like the problem's in tabhunter.
