### ISSUE TITLE
Access your data for all websites

### ISSUE THREAD

**Issue by abitrolly** [ericpromislow/tabhunter#137]
Why this extension needs "Access your data for all websites" permission beyond "Access browser tabs"?

**Comment by ericpromislow** [comment]
Here are the permissions the code requests:
* activeTab - for obvious reasons
* clipboardWrite - to handle copying the title and URLs
* storage - to store permissions
* bookmarks - to save tabs in a bookmark folder
* <all_urls> - so the extension is active for all URLs
* tabs - for obvious reasons

I don't see "Access your data for all websites" anywhere in the code, so I would assume firefox (and/or chrome) is converting these permission names to the above human-friendly text.

**Comment by abitrolly** [comment]
@ericpromislow https://addons.mozilla.org/en-US/firefox/addon/tabhunter/

![image](https://github.com/user-attachments/assets/6cef391c-6909-44c1-88f3-2121e6408443)

**Comment by abitrolly** [comment]
@ericpromislow for `tabs` vs `<all_urls>`, it looks like the latter is only needed if you want to run code inside web pages.

https://stackoverflow.com/questions/16096482/what-does-http-https-and-all-urls-mean-in-the-context-of-ch

It should not prevent extension from being activated though a button or a shortcut.
