### ISSUE TITLE
Tabhunter not always in sync after closing a tab

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ericpromislow/tabhunter#43]
```
Bring up Tabhunter.  Close a tab.  Sometimes the tab
still shows up in Tabhunter, and clicking on other tab
entries sometimes goes to a different tab.
```

Original issue reported on code.google.com by `eric.pro...@gmail.com` on 5 Mar 2013 at 9:15

**Comment by ericpromislow** [comment]
Should be fixed now that Tabhunter is targeting the webextensions API. To test before the next release, use the Firefox Developers' Edition, `about:debuggin`, load a temporary addon, pull up the tabhunter `manifest.json` file, and load by either pressing `Shift-Ctrl-T` or hitting the icon, now in the upper right bar.
