### ISSUE TITLE
TabHunter window does not open, stays in taskbar

### ISSUE THREAD

**Issue by reikred** [ericpromislow/tabhunter#62]
I have the exact same problem as described by the following reviewer last year:

"Several months ago tabhunter stopped working properly - launches in background and cannot bring to foreground so it's unusable Rated 3 out of 5 stars, by anonymoose on November 3, 2014"
From https://addons.mozilla.org/en-US/firefox/addon/tabhunter/reviews/641784/

When I open TabHunter (Ctrl-Y in my case), nothing happens, but upon closer inspection a  TH icon is created in the FIrefox (FF) group on the taskbar. This TH icon can however also not be opened by clicking the icon (in the FF group on the taskbar). Nothing happens when I click it.

Win10, firefox 40.0.3 and 41.0.1, not able to test elsewhere at the moment.

See next post for a list of extensions in use.

**Comment by reikred** [comment]
Here is the is list of extensions currently in use, as provides "extension list dumper 2":

Application: Firefox 41.0.1 (20150929144111)
Operating System: WINNT (x86-msvc)

- Adblock Plus 2.6.11
- Classic Theme Restorer 1.4.0
- Cleanest Addon Manager 7.0.1-signed
- CookieSwap 13.4.331.1-signed
- Duplicate in Tab Context Menu 1.0.9.1-signed
- Extension List Dumper 2 1.0.1
- Flashblock 1.5.18.1-signed
- LastPass 3.2.21
- Multifox 3.2.1
- Multifox Toolbar Button 1.05.1-signed
- Multiple Tab Handler 0.8.2015030601.1-signed
- Session Manager 0.8.1.7
- Tabhunter 1.0.5.1-signed
- Tree Style Tab 0.15.2015030601.1-signed

**Comment by reikred** [comment]
I can also report that I disabled ALL extensions except tabhunter, and still the TH window will not pop up. I'm fairly certain that it used in a recent version of firefox. There may be some bitrot going on with TH versus a newer FF.

**Comment by reikred** [comment]
One more observation: When the TH icon is in the taskbar, I found a specific trick to get TH up on the screen: First mouse1 the taskbar to get the list of FF icons, the mouse3 (right-click) the tabhunter icon and choose Maximize. That will indeed make the window appear, and one can use it. 

It may be that after doing this, the TH window will work normally, I have to test this after doing a FF restart.

**Comment by Lister0fSmeg** [comment]
The TH window opens off screen and for me, bringing it onto screen, closing the TH window did not fix it as it still opened up off screen. BTW I was using a higher resolution monitor which I have had to return.

I fixed it by opening about:config, typing tabhunter into the search and then altering the extensions.tabhunter.screenX and extensions.tabhunter.screenY option to a value which appears on screen. After doing that it now opens on screen.

BTW other people have also had this problem.

**Comment by ericpromislow** [comment]
Should be fixed now that Tabhunter is targeting the webextensions API. To test before the next release, use the Firefox Developers' Edition, `about:debuggin`, load a temporary addon, pull up the tabhunter `manifest.json` file, and load by either pressing `Shift-Ctrl-T` or hitting the icon, now in the upper right bar.
