### ISSUE TITLE
Sort by title

### ISSUE THREAD

**Issue by Tragen** [ericpromislow/tabhunter#64]
Please add an option to sort by title.

**Comment by druthers** [comment]
Sort by Title -- and also, Sort by URL. ... In other words, Sortable Columns, where clicking on a "column header" would sort the list, based on that column.

Sorting by URL would allow "listing" the open tabs for one website, together -- to help the user quickly move those tabs to a new window -- or to quickly close all the tabs (from that website).

( And perhaps, also add a "column" for Sort by Date -- i.e., the date of the webpage download, if that's possible ?)

**Comment by ericpromislow** [comment]
Done in 2.1.0.  Sorting by Recency added in 2.1.1 (so far Firefox only), which deals with the time a tab was last accessed.
