### ISSUE TITLE
>1.0.20 not working on Pale Moon

### ISSUE THREAD

**Issue by Lister0fSmeg** [ericpromislow/tabhunter#67]
Tab Hunter no longer works with Pale Moon and has not since 1.0.20 and not fully since 1.0.5.1-signed which was the last version which remembers the previously entered search term when TH is opened. On all later versions TH opens with a blank search term which means a previously searched term has to be re-entered which is a bit of a nuisance if a person is trying to close repeated tabs.

On all versions since 1.0.20 the TH window is none functional opening entirely blank with no tabs or search item visible.

ATM I am using 1.0.5.1-signed in order to use TH as I want.

**Comment by ericpromislow** [comment]
Problem 2 reported above is a dup of https://github.com/ericpromislow/tabhunter/issues/66 which I would have resolved as WONTFIX if github made that choice available -- see the bug for the reason why.

On firefox the search term *is* remembered.

As I wrote in bug #66 I'm not a Pale Moon user and don't have time to investigate why
these problems are appearing on it. I did report the problem in the PaleMoon forum, b
but didn't hear from them via notifications.

I fully welcome any one who wants to work on the Tabhunter port to Pale Moon. From
what I've seen, there is some porting work needed.

Meanwhile, the core of Tabhunter will be focused on staying up to date with changes
to Firefox.
