### ISSUE TITLE
Full Text Search Search Gone ?

### ISSUE THREAD

**Issue by swenjohnson** [ericpromislow/tabhunter#68]
I'm running TH 1.0.29 on FF 44.0.2, Yosemite 10.10.5. I don't see a tab for the full-text search.

Same thing for TH 1.0.29 on FF 45.0, Linux Mint Rebecca (17.1).

It worked fine on both OS's the last time I tried.

Am I the only one ?

**Comment by morspin** [comment]
I had to remove it to support dual-process Firefox. The Mozilla developer I talked to about it was dubious that full-text search would work for large numbers of tabs in dual-process Firefox. So it'll be a while before I run the experiment to see if it could work.

A pull request is always welcome though.

**Comment by ericpromislow** [comment]
Reinstated in version 3.0.0 -- Note that due to limitations in the new firefox API tabhunter will only search through active, loaded tabs, and will skip internal tabs, like mozilla's  `about:debugging`.

**Comment by swenjohnson** [comment]
Great !   Can't wait to try it.

-- Swen
    On Monday, June 11, 2018, 10:34:21 PM PDT, Eric Promislow <notifications@github.com> wrote:  
 
 
Closed #68.

**Comment by ericpromislow** [comment]
The search UI is a little different from the previous version. When you first press the "Search text in tabs" button, you get a list of the subset of tabs that can be searched in (active, non-internal pages), and then each search starts with that list and narrows it down to the list of actual hits. I think it's more refined, but then I spent about 2 hours on it, so there's room for improvement.
