### ISSUE TITLE
No More Keyboard Shortcut Invocation

### ISSUE THREAD

**Issue by AndydeCleyre** [ericpromislow/tabhunter#73]
Hi,

I'm on Arch Linux, and I used to use `ctrl`+`/` to summon this extension. I guess it just updated, and that keyboard shortcut no longer works. So I went to edit/check the preferences, but the preferences are gone in this version. So I checked the readme, and apparently it's now hardcoded to `shift`+`ctrl`+`5`, but that also does nothing over here.

tabhunter `2.0.0`
firefox `56.0`

**Comment by ericpromislow** [comment]
Yes I know

I had to port Tabhunter to a completely new API, and way I did prefs was completely obsolete. I find the Shift-Ctrl-5 combo doesn't even work on all my machines. Rest assured this is at the top of my backlog.

**Comment by AndydeCleyre** [comment]
Thanks very much for the continued development and the communication.

**Comment by raggoo** [comment]
So will the preferences be restored so that we may set our own hotkeys that we were used to?

Not quite understanding your reply.

Thanks.

**Comment by ericpromislow** [comment]
"this is at the top of my backlog" == "Yes. The next thing I work on will restore this functionality"

**Comment by ericpromislow** [comment]
You can find older versions at https://addons.mozilla.org/en-US/firefox/addon/tabhunter/versions/ -- no guarantee which addon versions will work with your particular browser.

**Comment by apothegm** [comment]
Looking forward to this fix.

Switched from Chrome to Firefox Quantum for performance improvements. Loved Tab Ahead and used it ALL the time. I guess it's because I'm so used to using IDEs like PHPStorm and Sublime to navigate around.

**Comment by ericpromislow** [comment]
Fixed in Tabhunter 2.0.7, currently works with FF Developer's Edition, fix should launch GA in version 60 or so.

**Comment by gauchotche** [comment]
shortcut works on ADDONS page in firefox, but not in regular tabs. Could you fix this please?

**Comment by ericpromislow** [comment]
It works for me (3.0.*). Which version of Tabhunter is this with? Which OS? What keyboard shortcut are you trying to set it to? Are there any pertinent messages in the console (accessible via Shift-Ctrl-J on Lin/Win, Shift-Cmd-J on macos)
