### ISSUE TITLE
After maff conversion the tabhunter option vanished from tools menu

### ISSUE THREAD

**Issue by Kurtking** [ericpromislow/tabhunter#74]
The removal was a FF script bc maff will be going away.  I had thousands of the archives, so I ran the script.  Today, I tried to use tabhunter and the tools menu option to invoke it is gone.  I don't know how to invoke it otherwise.

**Comment by ericpromislow** [comment]
Right now you need to click on the icon, which hasn't changed, but it's up in the toolbar. You might be able to invoke Tabhunter with Ctrl-Shift-T on macos, Ctrl-Shift-5 (five) elsewhere, but I'm getting mixed reports on its reliability.  

Thanks for putting up with a bit of turbulence as we move to the new Firefox extension world.
