### ISSUE TITLE
sorting options for matched tabs

### ISSUE THREAD

**Issue by equalsJeffH** [ericpromislow/tabhunter#77]
The matched tabs are by-default listed alphabetically by window title, yes? And there's no present way to alter that, yes?

It would be great if there were some sorting options one could choose on-the-fly, e.g., especially, to sort by least-recently-used-first.  That would greatly help me, an inveterate tab-hoarder, to be able to more easily grit teeth and close bunches of 'em.  Other possible sorting options: by URL, secondarily, reverse-alphabetic.

**Comment by ericpromislow** [comment]
Done in 2.1.0: added sorting by URL and window/tab-position. Hmmm, there's a `tab#lastAccessed` property....

**Comment by ericpromislow** [comment]
And done in 2.1.1
