### ISSUE TITLE
Configurable shortcut key

### ISSUE THREAD

**Issue by gauchotche** [ericpromislow/tabhunter#78]
thank you very much for this addon. I wouldn't be able to use firefox without it. Could you please put an option so that we can configure the shortcut key as we like?

**Comment by ericpromislow** [comment]
I'm working on it, but it entails modifying the core webextensions API, so I need to write a test suite for it, plus test my preference panel interactively on all of the mac, pc, and linux. The biggest bottleneck is going to be getting the change into Firefox 58.

**Comment by gauchotche** [comment]
Now with 57 the extension i used is no longer working. Do u know any which
works with quantum?

I use ctr+x to open tabhunter

**Comment by gauchotche** [comment]
Hello, any news on configurable hotkey? thanks

**Comment by ericpromislow** [comment]
Well, a month ago I submitted a patch that implemented my proposed addition to the WebExtensions API, `commands.update` https://bugzilla.mozilla.org/show_bug.cgi?id=1348589 . There was some discussion on another bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1421811) but nothing has happened.  The Moz team has been discussing this for over a year (https://bugzilla.mozilla.org/show_bug.cgi?id=1303384) without shipping anything. It took me a weekend to set up the development environment, add the method, add tests, and build a UI that works, but nothing has landed, including non-coding time spent with my family (it was the weekend after all).

**Comment by clach04** [comment]
I have the Jan 01 2018 version installed. I can't get the tab hunter window to show :(

* CTRL-5 - brings up the 5th tab
* The config entry says alt-shift-t - that brings up the Firefox Tools menu

**Comment by ericpromislow** [comment]
At this point, the best thing you could do is probably get a mozilla
account if you don't have one, and then go to
https://bugzilla.mozilla.org/show_bug.cgi?id=1348589 and say you need this
fix. Currently I have to set the shortcut in the manifest, but there's no
one setting I can
pick that won't conflict with something else.

**Comment by clach04** [comment]
Thanks, I made a quick post

**Comment by ericpromislow** [comment]
As of this week this works in the Firefox Developer's Edition. I expect it will go GA in version 60, or maybe 61.

**Comment by ericpromislow** [comment]
Go to `Tools | Add-ons`, select Tabhunter Preferences, and if the version of Firefox you're on supports modifying shortcut commands, you'll see an option to change the `Startup Key Sequence`. This feature is working in current developer versions of Firefox, but hadn't landed for version 59. The code is written so if changing commands is implemented, the option will be visible.

**Comment by clach04** [comment]
Woo Hoo! 🍰 I can confirm this is working for me with Developer Build under Windows.

**Comment by gauchotche** [comment]
Today I've upped to 60... problem is shortcut only works in the "ADDONS MANAGER" webpage, the other pages it doesn't work...

**Comment by gauchotche** [comment]
Please could dev look into it? the shorcut works in "addons manager" tab, but not in any other.

**Comment by ericpromislow** [comment]
Fixed in tabhunter 2.2.1

And as a workaround, the new shortcut takes effect if you change any other setting in the prefs area.

**Comment by gauchotche** [comment]
still not working. the only tab which the shortcut works is in the ADDONS page... anywhere else it doesn't work.
