### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Moilleadoir** [ericpromislow/tabhunter#79]
Is there any way to increase the tiny font size? Or is this a problem with web extensions in general?

![tabhunter2](https://user-images.githubusercontent.com/1229543/36139047-25a06274-10f0-11e8-8d40-f37a4ac08c0f.jpg)

**Comment by ericpromislow** [comment]
Should be doable via a pref.  I'm busy in Feb, can look at it next month

**Comment by Moilleadoir** [comment]
Excellent, thank you!

**Comment by ericpromislow** [comment]
Done in 2.0.6. Currently available for Firefox. I hope to port to Chrome sometime this weekend.
