### ISSUE TITLE
icon for tabhunter disappeared from toolbar after update to 2.1.3

### ISSUE THREAD

**Issue by wsmwk** [ericpromislow/tabhunter#81]
icon for tabhunter disappeared from toolbar after update to 2.1.3

**Comment by wsmwk** [comment]
The icon is not avaible from toolbar customize 

I have not tested further or restarted firefox, so is possible related to something else.

**Comment by ericpromislow** [comment]
Which  OS is this on? I gather you're talking Firefox, cuz I haven't uploaded a Chrome version for 2.1.3. And what happens if you upgrade to 2.1.4?  Is there anything in the javascript console?  What if you disable all your other extensions and restart?

**Comment by ericpromislow** [comment]
Closing because 2.1.5 is now out
