### ISSUE TITLE
UI Tweaking: Windows

### ISSUE THREAD

**Issue by rayman89** [ericpromislow/tabhunter#83]
Currently is hard to know which tabs are from which window when using tab hunter: I think it would be nice to implement some contractile separators for each tab and have an option to only show expanded current tab so that you can have focus on that but if someone prefers to have all expanded like it's now to have that too.

The ui I'm suggesting would be something like this (user would be on window 2 currently).

----------Window 1----------[+]
----------Window 2----------[-]
           *Tab 1
           *Tab 2
           *Tab 3
----------Window 3----------[+]
----------Window 4----------[+]

**Comment by ericpromislow** [comment]
Right now you can go to the Preferences panel on the Add-ons page and select the "Windows/Tab" sort-by option. You don't get the collapsing part, but I'd say this is close enough.

**Comment by rayman89** [comment]
I'm using that and I feel that it's still very messy. It's nice to be able to have focus on one windows. If you don't wanna do the collapsible thing can you add an option that just show tabs from current window?

**Comment by ericpromislow** [comment]
I would rather leverage the power of the search bar. I'm thinking that a
search that starts with "[n]" shows tabs only in window n. Searching
"[n:i-j]" shows tabs i through j (1-based because not all Tabhunter users
are C programmers). (And the numbers are the ones displayed in window/tab
view). We can even support python-type slicing (although 1-based):
"[3:5-]" : shows all tabs from #5 to end in window 3.
"[2:-8]" : show all tabs up to and including position 8 from window 2.

 I way prefer that to just adding more UI. And if I'm going to implement
the drag-drop thing you requested, I'd prefer to do it over a
non-collapsible widget.

**Comment by rayman89** [comment]
I see. Would it be much of a problem to add a drop down menu with preset filters for the listed tabs to display all windows, current window, Window 1, Window 2 etc. That preset would be by default always in "all windows" but if you could ir would be nice to add the option "show current windows tabs by default" to make the filter be set by default on "current window". Something like this:

![imagen](https://user-images.githubusercontent.com/5449042/39247553-58926dca-485f-11e8-9ad0-0453791419e6.png)

**Comment by ericpromislow** [comment]
Window selection in the pattern field added in version 2.1.7

**Comment by rayman89** [comment]
> *putting `{w:N}` at the start of a pattern shows only tabs in window N
> * putting `{w:N:T1-T2}` at the start of a pattern shows only tabs T1 through T2 in window N
> * putting `{w:N:T}` shows tabs T through the end in window N
> * putting `{w:N:-T}` shows tabs 1 through T in window N

Why so complicated? It's tabs not a complex database. I don't think users wanna be remembering this codes to input when they wanna see tabs from a specific window.  What's wrong with the drop down menu? or maybe a Window : (textbox) where 0 = all windows (some other symbol like #) = current window and "n"= (number) window.

**Comment by ericpromislow** [comment]
I did it this way because:
1. I don't have a personal use for it, and
2. it was a quick change to the JS code and needed no additional UI
