### ISSUE TITLE
UI tweaking:  Menus

### ISSUE THREAD

**Issue by rayman89** [ericpromislow/tabhunter#84]
Could you consider like we mentioned before a right click menu with all the options that are now on buttons to make the UI tidier?

**Comment by ericpromislow** [comment]
I'm not a fan of the way right-click menus work in the WebExtensions add-ons -- they're very clunky, because they're a separate menu off the standard context menu. So sorry, but it's going to be buttons and more buttons.  With 2.1.5 I'm using a "More..." button to hide extended functionality.
