### ISSUE TITLE
Default keymapping for TabHunter

### ISSUE THREAD

**Issue by clach04** [ericpromislow/tabhunter#86]
Related to https://github.com/ericpromislow/tabhunter/issues/78.

This may be an unsolvable problem with the different platforms that Firefox runs on. Any recommendations for cross platform default key combination?

I'm currently using CTRL-SHIFT-u - it doesn't collide with either system or Firefox default key bindings.

**Comment by ericpromislow** [comment]
Maybe something with a number (which has to be unshifted), like Ctrl-5. But there aren't a whole lot of choices.  Ctrl-Shift letter, Ctrl-letter, Ctrl-number, and Ctrl-<arrow key>

**Comment by clach04** [comment]
CTRL-number (no shift) takes you to that tab number in Firefox under Windows. CTRL-SHIFT-number doesn't conflict.

It may simply not be possible to pick a good cross platform default, I'm so happy https://github.com/ericpromislow/tabhunter/issues/78 is resolved 😀
