### ISSUE TITLE
More UI suggestions

### ISSUE THREAD

**Issue by rayman89** [ericpromislow/tabhunter#87]
I think, idk if you agree with me or not that it would be sufficient to just have 1 search bar called "search" and filter by url and title at the same time. So typing "youtube" would search for "youtube" on title and url. That would remove some space and I think it wouldn't change much.

An other thing I don't quite understand is what the button "done" does. It seems to just close the popup. I think that can be removed and the user can just click outside of the popup to cancel whatever they were doing.

The "go" button could taken off too if you change left click on tab title to go to that tab and keep control + click for selection of individual tabs or if you don't want that maybe right clicking on a tab would sent you there and left click would stay like it's now.

You could also put a "bookmark tabs" button there instead of using the "more" button and when it's clicked it displays only this 

![imagen](https://user-images.githubusercontent.com/5449042/39248379-88635562-4861-11e8-85d6-5b1daac3c42d.png)

same for the "move tabs" functionality. (have a button that on click just displays this)

![imagen](https://user-images.githubusercontent.com/5449042/39248417-a8d020aa-4861-11e8-8b85-38316f576a93.png)

**Comment by morspin** [comment]
The "Done" button is there just because it made sense back in version 0.1
or whatever I first shipped Tabhunter at, and it was probably in the tab
picker that inspired it. After 10 years it makes sense to fix up the UI a
bit.

I see I should also finally localize Tabhunter. Would make an ideal pull
request for someone who wants to contribute but doesn't have mad JS skillz

**Comment by rayman89** [comment]
I willing to translate to Spanish Portuguese and Italian if you want me to. Could you implement #82 #83 #85 #87 in some way or another?

What about the other suggestions besides the "done" button?

**Comment by ericpromislow** [comment]
Sure, I'll get right on it right away

**Comment by ericpromislow** [comment]
This issue needs to be replaced by tighter issues that each address a single problem.
