### ISSUE TITLE
what is purpose of the UI that the [More] button shows?

### ISSUE THREAD

**Issue by equalsJeffH** [ericpromislow/tabhunter#88]
what is purpose of the UI that the [More] button shows?  I cannot really figure it out....

**Comment by ericpromislow** [comment]
That's where all the UI that doesn't fit in the core mission of finding
tabs will go.

Currently it lets you move the selected tabs to a different window (firefox
and chrome) or to put them in a bookmark folder (firefox only).  When I get
a chance, I'll duplicate the pref settings there, and put future features
in there as well.

**Comment by ericpromislow** [comment]
Press "More..." and select some tabs.
Choose a window in the window dropdown list.
Press the "Move the tabs" button.

Similar for bookmarks (not available on chrome).

More info at https://addons.mozilla.org/en-US/firefox/addon/tabhunter/
