### ISSUE TITLE
Selecting a tab from the search results loses focus if it is in a different browser window

### ISSUE THREAD

**Issue by toad01** [ericpromislow/tabhunter#89]
If I select a tab from the search results that is in a different browser window from the one in which I initiated the search, that tab only appears momentarily before losing focus and I am returned to the search window. This has happened since 'upgrading' to Firefox 60.

**Comment by ericpromislow** [comment]
I don't observe this on FF 60 on OSX. Which OS does this happen in? Are there any relevant messages in the console?

**Comment by toad01** [comment]
I'm using Windows 7. Not certain what you mean by messages in the console, but I'm not seeing anything else unusual. Perhaps it is just me, as I would have thought others would have reported such a fundamental issue!

**Comment by ericpromislow** [comment]
@toad01 Under Tools, look for something like "Web Developer > Browser Console"

I just upgraded my firefox on linux to v60, and no problem.

Windows is tougher. No Win at the office, and I just have a laptop running windows 10 at home, but I'll have a look. In the meantime, what if you set the pref to close the tabhunter window after selecting a tab?

**Comment by toad01** [comment]
Close On Go was already selected. If I deselect it, it works ok! In either case the tabhunter window closes.

The console shows the following error (with and without Close On Go selected):

unreachable code after return statement  tabhunter.js:856:4
Security Error: Content at moz-nullprincipal:{8d89e258-8d1d-40e6-a015-fbd52561834b} may not load data from moz-extension://7051a032-70f7-4f37-8839-654b18dfad1b/popup/tabhunter.js.
NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIWebNavigation.loadURI]  viewSource-content.js:286

**Comment by ericpromislow** [comment]
not reproduced
