### ISSUE TITLE
Windows command shortcuts aren't saved

### ISSUE THREAD

**Issue by ericpromislow** [ericpromislow/tabhunter#92]
Also Ctrl-N on Windows goes to the 5th tab

**Comment by basilevs** [comment]
> I assume you have the "Ctrl-1 for Item 1 etc." pref checked
I don't. Its empty as any other settings on pref page:
![image](https://user-images.githubusercontent.com/650857/40739475-8a1f3cce-6470-11e8-9547-7a05f1c250c7.png)
Ctrl+N opens a tab of a given number without any extensions. This is a default behavior.

**Comment by ericpromislow** [comment]
I tested on a laptop running windows 10 and got Ctrl-Shift-U to work, including after a full restart.
 
From `Help | Keyboard Shortcuts` I see almost all the allowed key combinations are already used by some aspect of Firefox and they take priority. Maybe something like `Shift-Home` would work for you?

**Comment by basilevs** [comment]
Firefox 61.0b9, Windows 10, shortcut tried: Ctrl-/

**Comment by ericpromislow** [comment]
First, not all keystrokes are supported by firefox -- see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands and search for “Key combinations”

Second, the tabhunter command setting doesn’t override a default firefox setting so for example if you try to map the command to Shift-Ctrl-T, that keystroke is still going to bring up the most recently closed tab (with default North American bindings).

And the extension should refuse "Ctrl-/" -- it does on linux

**Comment by basilevs** [comment]
Well, as you can see from report, I've tried plenty of combinations. None have visible effect on screen.

**Comment by ericpromislow** [comment]
I can't watch your report -- I only have mac and linux machines. If you could put it on a web site I can watch it. If I try entering the shortcut 'Command-/' on mac I get an alert box stating "Can't support a key sequence of 'command+/'" as expected.

You might see other messages by showing the console. I think on windows you can bring it up with 'Ctrl-Shift-J'.

**Comment by basilevs** [comment]
Google Chrome can open MHT files. I know this sounds funny in context of Firefox plugin development :)

**Comment by ericpromislow** [comment]
I didn't realize I broke the add-ons page prefs when I "copied" them into the app.  Fixed in 8027487135a7eb16c46201769968e6ddf37fd1d3 . Thanks for reporting the problem.
