### ISSUE TITLE
Tabhunter versions -- and Dark Screen Display issue

### ISSUE THREAD

**Issue by druthers** [ericpromislow/tabhunter#97]
I have a Windows 7 computer, running Firefox v50.0.1 -- where Tabhunter "was" working OK -- ( with one "major" exception). ... I intend to NOT update Firefox on this one computer, because of a large number of needed extensions that cannot be updated -- (there are no replacements for this, or any version of Firefox).

I always have the Automatic Updates for Tabhunter set to "Off" -- but somehow Tabhunter got updated to version 3.0.4 -- which does not work at all, on Firefox version 50.

Question:

Where can I download the "newest" (old) Tabhunter version that is compatible with Firefox v50.0.1?

#2 --

I mentioned that Tabhunter "was" working OK -- with one "major" exception. ... And that exception apparently applies to ALL versions of Tabhunter, new and old:

Namely, when running Windows with a "dark screen display" (with light fonts), Tabhunter is currently Useless -- because ALL Tabhunter fonts are Invisible (black on black) -- until after ALL Firefox Tabs are switched to a "light screen display" (with dark fonts). But that switching of the display takes a relatively long time -- and that delay interferes with the convenient use of Tabhunter. ... (Note: I always use a dark screen display with light fonts, when running Firefox.)

... Please, can you find a way to make all of Tabhunter's display fonts, display "normally" (such as white on black) when a Dark Screen Display is being used in Firefox?

Thank you,

Bill K

**Comment by ericpromislow** [comment]
#1: You can find all released versions at https://addons.mozilla.org/en-US/firefox/addon/tabhunter/versions/

As for your second question, it won't surprise you to hear that I'm using whatever the stock color scheme is. Is there a theme you can point me to? And if I use it, how do I stop using it?

**Comment by druthers** [comment]
> You can find all released versions at
> https://addons.mozilla.org/en-US/firefox/addon/tabhunter/versions/

Thanks... Now I have Tabhunter v1.0.29 reinstalled - and that's newer than the one I was using.


> As for your second question, it won't surprise you to hear that I'm using whatever the stock color scheme is. Is there a theme you can point me to? And if I use it, how do I stop using it?
>

Well, I haven't been using "themes" to switch between "Light background + Dark fonts" and "Dark background + Light fonts".

Instead, I use the Firefox "Color Toggle" add-on (latest version 0.16.1) -- that Toggles colors between two user-configured color profiles... Here's the website:

https://addons.mozilla.org/en-US/firefox/addon/color-toggle/
https://addons.mozilla.org/en-US/firefox/addon/color-toggle/versions/

( Note: Color Toggle is Not compatible with Firefox "Quantum" browsers, versions 57+.)

( For specifics -- and ideas? -- Color Toggle's developer, Nathan Baker, can be e-mailed at - EliteBadger@gmail.com . His other website is - https://github.com/nathan-b/colortoggle/ .)


I like your "old" Tabhunter v1.0.29, because the color of its window background is determined by a Windows setting. In Windows 7, that setting is in "Personalization" > "Window Color and Appearance" > "Window Color". The result is that the "Window background" remains unchanged (light blue + black font), with Color Toggle in either its Light, or Dark display modes.

Perhaps Nathan Baker might have some ideas on how to achieve that -- with, or without Themes -- in Firefox Quantum?

Another, related note:

When I log into AOL-Verizon, and I'm in Dark display mode, a dialog appears that says: "It looks like you're in High Contrast Mode. Would you like to switch... OK/Cancel." ... I don't know how they detect the "contrast mode" (that's not related to themes), but they do...

Thanks!

Bill

**Comment by ericpromislow** [comment]
Dark theme support added in version 3.2.0 -- commit 243131c
