### ISSUE TITLE
Text field not focused when Tabhunter in overflow menu

### ISSUE THREAD

**Issue by imd** [ericpromislow/tabhunter#98]
Steps to reproduce:
1. Right-click Tabhunter icon and choose "Pin to Overflow Menu"
2. Use keyboard shortcut (default ctrl-5) to pull up Tabhunter dialog
3. Try to type

Result: keystrokes are sent thru to the current tab

Expected result: keystrokes are captured by Tabhunter dialog and text is entered in Pattern text input

**Comment by ericpromislow** [comment]
Reproduced, but please note that popup extensions when launched from the overflow menu are still clipped.

**Comment by ericpromislow** [comment]
Reproduced over a year later. This looks like a mozilla bug that hasn't had any work done on it in years. Closing this issue because there's nothing I can do about it on the extension side.
