### ISSUE TITLE
API change - no longer installs

### ISSUE THREAD

**Issue by grtodd** [ericpromislow/tabhunter#99]
Either from a file went built locally, or from Mozilla/Firefox addons manager. Likely due to another API or format change for addons.

**Comment by ericpromislow** [comment]
Could you clarify? What do you mean by "from a file went built locally" -- did you download the source and run make yourself (and I definitely welcome this)? Can you bring up the console and include some error messages? And what do you mean by a "format change for addons"?

**Comment by ericpromislow** [comment]
Didn't hear anything after a year. Closing.
